version: 0.0
os: linux
files:
- source: /
 destination: /home/ubuntu/devops-class-node-app

permissions:
- object: /
   pattern: "**"
   owner: ubuntu
   group: ubuntu

hooks:
ApplicationStop:
   - location: bin/app-stop
     timeout: 10
     runas: ubuntu

AfterInstall:
   - location: bin/install-pkgs