version: '2'
services:
  devops-class-node-app:
    image:
      devops-class-node-app
    ports:
     - "8080:8080"
    depends_on:
     - mongo
  mongo:
    image: mongo
    ports:
     - "27017:27107"
    volumes:
     - /data/db